### PR TITLE
Update UtilityTests.cs

### PR DESCRIPTION
**Pull request by divzi-p**
added test comment

## Purpose

* ...

## Does this introduce a breaking change?

```
[ ] Yes
[ ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

### CODE REVIEW

**Comment by divzi-p** [comment]
#1#card-48389413

**Comment by divzi-p** [comment]
#card-48389413

**Comment by divzi-p** [comment]
https://github.com/divzi-p/openhack-devops-team/projects/1#card-48389413

**Review by truesrini — APPROVED** [review]
approve

**Pull request merged**
